# For production
version: '3.9'
services:
  database:
    image: postgres:alpine
    container_name: dandirizky-database
    hostname: database
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    env_file:
    - .env
    restart: always
  app:
    image: dandirizkyy/dandirizky-w15-app
    container_name: dandirizky-app
    build: .
    ports:
    - 4001:4001
    env_file:
    - .env
    depends_on:
    - database
    restart: always
volumes:
  postgres: